version: '3.4'

services:
  lojan-1application.api:
    image: ${DOCKER_REGISTRY-}lojan1applicationapi
    build:
      context: .
      dockerfile: lojaN-1Application.API/Dockerfile
    ports: 
      - "8080:80"
      - "5001:432"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=postgres;Username=postgres;Password=postgres"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
